### PR TITLE
Clean ja-JP

### PR DESCRIPTION
**Pull request by KevinZonda**

### CODE REVIEW

**Comment by KevinZonda** [comment]
@Michael18811380328 Hi! Since you are not a member of @LGBT-CN, so I can't assign to you or ask CR from you. However, I'm not good at Japanese. I'll be appreciated that if you could review this and leave some comments. Thanks!

**Comment by Michael18811380328** [comment]
Thanks a lot. I found the ja-jp page should be same to home page too.

**Comment by Michael18811380328** [comment]
You can merge this PR to master directly.

**Comment by KevinZonda** [comment]
> You can merge this PR to master directly.

Thank you!

**Pull request merged**
