### PR TITLE
[Future] add counter

### PR DESCRIPTION
**Pull request by KevinZonda**
- [x]  Signature tag
- [x] CI support

### CODE REVIEW

**Review by scvoet — APPROVED** [review]

**Comment by KevinZonda** [comment]
`SIGN` tag has been finished at https://github.com/LGBT-CN/signature-counter/commit/1770e755d82e4ea755eb9ae85c4bbeef4691b7be
`COUNT` tag has been finished at https://github.com/LGBT-CN/signature-counter/commit/429b8617b2ea9e70abe76a7a9f1ab26365fa0290

**Comment by KevinZonda** [comment]
@scvoet Now CI works, but something may need to be changed:

https://github.com/LGBT-CN/LGBTQIA-in-China/blob/b37f238165a61a6e5334b974b791a5a2032be1ad/.github/workflows/count.yml#L22-L23

Also,

https://github.com/LGBT-CN/signature-counter/blob/d6059885d5853ded7319cf7a73c23cbb59976f38/src/main.rs#L37-L39

**Comment by scvoet** [comment]
@KevinZonda 诶，这些为什么要改(

**Comment by KevinZonda** [comment]
@scvoet 那就直接合并！

**Comment by scvoet** [comment]
@KevinZonda 好

**Pull request merged**
