### PR TITLE
fix error svg files

### PR DESCRIPTION
**Pull request by Michael18811380328**
页面中 svg 图标没有显示，控制台报错，暂时注释一下。支持这个项目！

### CODE REVIEW

**Comment by Michael18811380328** [comment]
也可以加上 svg 图标，这个 PR 我就关闭了。

**Review by KevinZonda — CHANGES_REQUESTED** [review]
Before:
image
After:
image

Hi, I think it is caused by network issue of GitHub. 

https://github.com/LGBT-CN/LGBTQIA-In-China/blob/fe5f69f223ce577f7361fe01a68e9b7f3d3af65a/index.html#L64

We could try replacing it to jsDelivr or FastGit

**Comment by KevinZonda** [comment]
Hi, it maybe fixed at #91 ?

**Comment by KevinZonda** [comment]
Fixed at da05b950d13979fb61258dbaf2382ed059446c7d

**Comment by KevinZonda** [comment]
Thank you for your help!

**Comment by Michael18811380328** [comment]
Well down!

**Pull request closed without merging**
