### PR TITLE
贡献两篇原创文章

### PR DESCRIPTION
**Pull request by BigCoke233**

### CODE REVIEW

**Comment by KevinZonda** [comment]
LGTM, but are these markdown marks?
image

image

**Comment by BigCoke233** [comment]
Yes, idk why they don't get parsed.

**Comment by KevinZonda** [comment]
> Yes, idk why they don't get parsed.

Hi, @BigCoke233, i think that marks didn't be parsed is caused by surrounded words.

Looks like

`我好**爱**你` will not be the same as `我好 **爱** 你`. I will solve it if I'm free. :)

**Comment by BigCoke233** [comment]
okay, thanks

**Pull request merged**
