### PR TITLE
optimise franch translate

### PR DESCRIPTION
**Pull request by KevinZonda**

### CODE REVIEW

**Comment by Cubik65536** [comment]
我写的原文是`支持者`因为有部分参考英语版本：

> You can view the list of **supporters** in the original text.

这么更改（改成`签署者`）在我看来并不会出现问题

**Comment by KevinZonda** [comment]
> 我写的原文是`支持者`因为有部分参考英语版本：
> 
> > You can view the list of **supporters** in the original text.
> 
> 这么更改（改成`签署者`）在我看来并不会出现问题

cool, cuz by wikipedia, the define of souteneurs is
> Noun. souteneur (plural souteneurs) A man who protects a prostitute and lives off her earnings

so i just think there'll be sth wrong XD

**Comment by KevinZonda** [comment]
anyway, i'll merge it

**Pull request merged**
